# -*- coding: utf-8 -*-
"""Menú mensual 2.0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u8yhNWxpMa7Iibcy-MZoIfKjOtN2cwBq
"""

from random import randrange

#genero las listas con cada comida por estación
snacks=['tostadas con queso untable', 'tostadas con huevo y tomate', 'yogurt con cereales', 'pancito con manteca', 'yogurt con frutos secos', 'yogurt con frutas', 'hotcakes con frutas', 'frutas']
comidas_invierno=['guiso de lentejas', 'guiso de arroz','guiso de fideos' ,'tortilla de papa', 'pastas salteadas con vegetales', 'tarta de ricota con acelga', 'tarta de zapallito con queso', 'empanadas de pollo', 'empanadas de carne', 'bife con zanahoria y huevo', 'supremas de pollo con tomate y huevo', 'ñoquis con salsa', 'fideos con salsa', 'ravioles con crema', 'lasagna de pollo, ricota y jamón', 'pizza', 'tarta de pollo', 'pastel de papa', 'milanesa de carne con puré', 'milanesa de pollo con papas y batatas al horno', 'pollo a la provenzal con fideos', 'tarta de espinaca y huevo', 'pizza de jamón y morrones', 'cabutia al horno relleno', 'polenta con tuco y queso']
comidas_verano=['tortilla de papa', 'pastas salteadas con vegetales', 'ensalada de lechuga, tomate, queso y pollo', 'bife con zanahoria y huevo', 'tarta de atún y huevo', 'supremas de pollo con tomate y huevo', 'ñoquis con salsa', 'fideos con salsa', 'ravioles con crema', 'ensalada cesar', 'pizza', 'tarta de pollo', 'tarta de jamón y queso', 'milanesa de carne con ensalada', 'milanesa de pollo con ensalada', 'pollo a la provenzal con fideos', 'tarta de espinaca y huevo', 'pizza de jamón y morrones', 'arroz con atún y huevo']
infusiones=['café con leche', 'mate', 'mate cocido']

#saco una cantidad aleatoria por día.
dias=int(input('Ingrese la cantidad de días para los que quiere realizar el menú: '))
estacion=int(input('Ingrese 1 si estamos en verano-primavera o 2 si estamos en invierno-otoño: '))

if estacion == 1:
  comidas_estacion=comidas_verano
elif estacion == 2:
  comidas_estacion=comidas_invierno
else:
  print('Metiste cualquier cosa, máquina.')

desayunos=[snacks[randrange(len(snacks))] for i in range(dias)]
almuerzos=[comidas_estacion[randrange(len(comidas_estacion))] for i in range(dias)]
meriendas=[snacks[randrange(len(snacks))] for i in range(dias)]
cenas=[comidas_estacion[randrange(len(comidas_estacion))] for i in range(dias)]
planificacion=tuple(zip(desayunos, almuerzos, meriendas, cenas))

for e, dia in enumerate(planificacion):
  print(f'Día {e+1}: \n Desayuno: {dia[0]} \n Almuerzo: {dia[1]} \n Merienda: {dia[2]} \n Cena: {dia[3]}')

menus=[{'Nombre': 'tostadas con queso untable',
  'Ingredientes': ('pan lactal', 'pan lactal', 'queso untable')},
 {'Nombre': 'tostadas con huevo y tomate',
  'Ingredientes': ('pan lactal', 'pan lactal', 'huevo', 'tomate')},
 {'Nombre': 'yogurt con cereales', 'Ingredientes': ('yogurt', 'cereales')},
 {'Nombre': 'pancito con manteca',
  'Ingredientes': ('pan lactal', 'manteca', 'pan lactal', 'manteca')},
 {'Nombre': 'yogurt con frutos secos',
  'Ingredientes': ('yogurt', 'frutos secos')},
 {'Nombre': 'yogurt con frutas',
  'Ingredientes': ('banana', 'naranja', 'manzana', 'yogurt')},
 {'Nombre': 'hotcakes con frutas',
  'Ingredientes': ('huevo', 'azúcar', 'harina', 'esencia de vainilla', 'avena', 'leche', 'banana', 'banana')},
 {'Nombre': 'frutas', 'Ingredientes': ('banana', 'manzana', 'naranja')},
 {'Nombre': 'café con leche', 'Ingredientes': ('café', 'leche', 'azúcar')},
 {'Nombre': 'mate', 'Ingredientes': ('yerba', 'azúcar')},
 {'Nombre': 'mate cocido', 'Ingredientes': ('mate cocido', 'leche', 'azúcar')},
 {'Nombre': 'guiso de lentejas',
  'Ingredientes': ('papa', 'papa', 'zanahoria', 'aceite', 'ajo', 'carne', 'cebolla', 'salsa de tomate', 'laurel', 'morrón', 'lentejas')},
 {'Nombre': 'guiso de arroz',
  'Ingredientes': ('papa', 'papa', 'zanahoria', 'aceite', 'ajo', 'carne', 'cebolla', 'salsa de tomate', 'laurel', 'morrón', 'arroz')},
 {'Nombre': 'guiso de fideos',
  'Ingredientes': ('papa', 'papa', 'zanahoria', 'aceite', 'ajo', 'carne', 'cebolla', 'salsa de tomate', 'laurel', 'morrón', 'fideos')},
 {'Nombre': 'tortilla de papa',
  'Ingredientes': ('papa', 'papa', 'huevo', 'huevo', 'huevo', 'aceite')},
 {'Nombre': 'pastas salteadas con vegetales',
  'Ingredientes': ('fideos', 'morrón', 'zanahoria', 'berenjena', 'cebolla', 'caldo de verduras', 'queso rallado')},
 {'Nombre': 'tarta de ricota con acelga',
  'Ingredientes': ('ricota', 'acelga', 'masa de tarta', 'aceite', 'cebolla', 'cebolla', 'ajo', 'huevo', 'huevo', 'queso rallado')},
 {'Nombre': 'tarta de zapallito con queso',
  'Ingredientes': ('aceite', 'zapallito', 'zapallito', 'zapallito', 'cebolla', 'queso cremoso', 'aceite')},
 {'Nombre': 'empanadas de pollo',
  'Ingredientes': ('pollo', 'aceite', 'aceite', 'cebolla', 'cebolla', 'morrón', 'huevo', 'huevo', 'aceitunas')},
 {'Nombre': 'empanadas de carne',
  'Ingredientes': ('carne', 'aceite', 'aceite', 'cebolla', 'cebolla', 'morrón', 'huevo', 'huevo', 'aceitunas')},
 {'Nombre': 'bife con zanahoria y huevo',
  'Ingredientes': ('bife', 'zanahoria', 'huevo', 'huevo', 'aceite', 'vinagre')},
 {'Nombre': 'supremas de pollo con tomate y huevo',
  'Ingredientes': ('pollo', 'tomate', 'huevo', 'huevo', 'aceite', 'vinagre')},
 {'Nombre': 'ñoquis con salsa',
  'Ingredientes': ('ñoquis', 'salsa de tomate', 'cebolla')},
 {'Nombre': 'fideos con salsa',
  'Ingredientes': ('fideos', 'salsa de tomate', 'cebolla')},
 {'Nombre': 'ravioles con crema',
  'Ingredientes': ('ravioles', 'crema', 'cebollita de verdeo')},
 {'Nombre': 'lasagna de pollo, ricota y jamón',
  'Ingredientes': ('laminas de lasagna', 'pollo', 'cebolla', 'ajo', 'ricota', 'jamón', 'queso cremoso')},
 {'Nombre': 'pizza',
  'Ingredientes': ('harina', 'aceite', 'levadura', 'muzzarella', 'salsa de tomate')},
 {'Nombre': 'tarta de pollo',
  'Ingredientes': ('masa de tarta', 'pollo', 'cebolla', 'morrón', 'aceite', 'caldito de gallina', 'huevo', 'huevo', 'crema', 'ajo')},
 {'Nombre': 'pastel de papa',
  'Ingredientes': ('papa', 'papa', 'papa', 'carne picada', 'cebolla', 'morrón', 'ajo', 'aceite', 'queso cremoso')},
 {'Nombre': 'milanesa de carne con puré',
  'Ingredientes': ('milanesas de carne', 'pan rallado', 'huevo', 'papa', 'huevo', 'leche', 'manteca')},
 {'Nombre': 'milanesa de pollo con papas y batatas al horno',
  'Ingredientes': ('milanesas de pollo', 'pan rallado', 'huevo', 'papa', 'papa', 'batata', 'batata')},
 {'Nombre': 'pollo a la provenzal con fideos',
  'Ingredientes': ('pollo', 'provenzal', 'fideos', 'manteca')},
 {'Nombre': 'tarta de espinaca y huevo',
  'Ingredientes': ('masa de tarta', 'espinaca', 'cebolla', 'crema', 'queso untable', 'queso cremoso')},
 {'Nombre': 'pizza de jamón y morrones',
  'Ingredientes': ('harina', 'aceite', 'levadura', 'muzzarella', 'salsa de tomate', 'jamón', 'morrón')},
 {'Nombre': 'cabutia al horno relleno',
  'Ingredientes': ('cabutia', 'queso cremoso', 'choclo', 'papa', 'batata', 'zanahoria')},
 {'Nombre': 'polenta con tuco y queso',
  'Ingredientes': ('polenta', 'caldo de gallina', 'queso', 'salsa de tomate')},
 {'Nombre': 'ensalada de lechuga, tomate, queso y pollo',
  'Ingredientes': ('lechuga', 'tomate', 'tomate', 'queso cremoso', 'queso cremoso', 'pollo')},
 {'Nombre': 'tarta de atún y huevo',
  'Ingredientes': ('masa de tarta', 'atún', 'cebolla', 'morrón', 'aceite', 'huevo', 'huevo', 'queso')},
 {'Nombre': 'ensalada cesar',
  'Ingredientes': ('lechuga', 'pan lactal', 'pollo', 'queso rallado', 'huevo', 'aceite', 'vinagre')},
 {'Nombre': 'tarta de jamón y queso',
  'Ingredientes': ('masa de tarta', 'jamón', 'queso cremoso', 'queso cremoso', 'huevo', 'huevo', 'huevo', 'crema')},
 {'Nombre': 'milanesa de carne con ensalada',
  'Ingredientes': ('milanesas de carne', 'pan rallado', 'huevo', 'lechuga', 'tomate', 'aceite', 'vinagre')},
 {'Nombre': 'milanesa de pollo con ensalada',
  'Ingredientes': ('milanesas de pollo', 'pan rallado', 'huevo', 'lechuga', 'tomate', 'aceite', 'vinagre')},
 {'Nombre': 'arroz con atún y huevo',
  'Ingredientes': ('arroz', 'atún', 'huevo', 'huevo', 'huevo')},
 {'Nombre': 'café con leche', 'Ingredientes': ('café', 'leche', 'azúcar')},
 {'Nombre': 'mate', 'Ingredientes': ('yerba', 'azúcar')},
 {'Nombre': 'mate cocido', 'Ingredientes': ('mate cocido', 'leche', 'azúcar')}]

#busco los ingredientes en los menus
ingredientes=[]
for desayuno in desayunos:
  for menu in menus:
    if desayuno in menu['Nombre']:
      for i in menu['Ingredientes']:
        ingredientes.append(i)
for almuerzo in almuerzos:
  for menu in menus:
    if almuerzo in menu['Nombre']:
      for i in menu['Ingredientes']:
        ingredientes.append(i)
for merienda in meriendas:
  for menu in menus:
    if merienda in menu['Nombre']:
      for i in menu['Ingredientes']:
        ingredientes.append(i)
for cena in cenas:
  for menu in menus:
    if cena in menu['Nombre']:
      for i in menu['Ingredientes']:
        ingredientes.append(i)
print(ingredientes)

#conteo para el supermercado
supermercado=[(ingrediente, ingredientes.count(ingrediente)) for ingrediente in ingredientes]
supermercado_limpia=set(supermercado)
supermercado_limpia